[tool.poetry]
name = "geo-activity-playground"
version = "0.1.0"
description = ""
authors = ["Martin Ueding <mu@martin-ueding.de>"]
license = "MIT"

[tool.poetry.scripts]
activity = "geo_activity_playground.__main__:main"
explorer = "geo_activity_playground.explorer.__main__:main"
explorer-video = "geo_activity_playground.explorer.video:main"
geo-heatmap = "geo_activity_playground.heatmap:main"
geo-strava = "geo_activity_playground.strava.api_access:main"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
numpy = "^1.22.4"
gpxpy = "^1.5.0"
click = "^8.1.3"
pandas = "^2.0"
scipy = "^1.8.1"
fitdecode = "^0.10.0"
requests = "^2.28.1"
Pillow = "^9.2.0"
tqdm = "^4.64.0"
matplotlib = "^3.6.3"
stravalib = "^1.3.3"
appdirs = "^1.4.4"
pyarrow = "^12.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.961"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
